#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../config/docker/ && pwd )"

read -p "Please enter your Docker Hub username: " username
read -p "Please enter your preferred Docker repository name [default: experiments]: " repository
repository=${repository:-experiments}

echo -n "$username" > "$DIR/username.txt"
echo -n "$repository" > "$DIR/repository.txt"

echo "Docker configuration saved."