#!/bin/bash
set -e
set -x

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update -qq
sudo apt-get -qq -y install linux-image-extra-$(uname -r) linux-image-extra-virtual
sudo apt-get -qq -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
sudo apt-get -qq -y install docker-ce